[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm install --legacy-peer-deps"]

[phases.build]
cmds = [
  "rm -rf .next/cache",
  "rm -rf node_modules/.cache",
  "npm run build"
]

[variables]
SKIP_ENV_VALIDATION = "true"
NODE_ENV = "production"

[start]
cmd = "npm start"
